In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales_recruitment_synthetic_200.csv")

In [3]:
print(df.head())

   age  gender  years_experience highest_education  technical_test_score  \
0   46  Female              12.7       High School                    67
1   41    Male              12.1        Bachelor's                    41
2   40  Female              12.5        Bachelor's                    69
3   38  Female              11.4       High School                    61
4   27    Male               3.9           Diploma                    59

   interview_rating  communication_assessment  leadership_assessment  \
0               8.4                       5.0                    3.9
1               8.2                       3.7                    4.8
2               8.0                       8.2                    5.6
3               7.7                       5.5                    7.8
4               7.7                       6.6                    7.3

   expected_salary_gbp  previous_job_tenure_years hired  \
0                60000                        2.5   Yes
1                44500                        3.6   Yes
2                55500                        1.6   Yes
3                57000                        2.5   Yes
4                37500                        1.3   Yes

   manager_satisfaction_after_one_year  sales_achieved_after_one_year_gbp  \
0                                  7.7                           132000.0
1                                  7.2                           103200.0
2                                 10.0                           157000.0
3                                  6.8                           116200.0
4                                  5.4                            50000.0

  retained_after_one_year
0                      No
1                     Yes
2                     Yes
3                     Yes
4                     Yes

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv("sales_recruitment_synthetic_200.csv")

In [9]:
df.head()

,age,gender,years_experience,highest_education,technical_test_score,interview_rating,communication_assessment,leadership_assessment,expected_salary_gbp,previous_job_tenure_years,hired,manager_satisfaction_after_one_year,sales_achieved_after_one_year_gbp,retained_after_one_year
0,46,Female,12.7,High School,67,8.4,5.0,3.9,60000,2.5,Yes,7.7,132000.0,No
1,41,Male,12.1,Bachelor's,41,8.2,3.7,4.8,44500,3.6,Yes,7.2,103200.0,Yes
2,40,Female,12.5,Bachelor's,69,8.0,8.2,5.6,55500,1.6,Yes,10.0,157000.0,Yes
3,38,Female,11.4,High School,61,7.7,5.5,7.8,57000,2.5,Yes,6.8,116200.0,Yes
4,27,Male,3.9,Diploma,59,7.7,6.6,7.3,37500,1.3,Yes,5.4,50000.0,Yes

In [10]:
df.describe()

,age,years_experience,technical_test_score,interview_rating,communication_assessment,leadership_assessment,expected_salary_gbp,previous_job_tenure_years,manager_satisfaction_after_one_year,sales_achieved_after_one_year_gbp
count,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,112.000000,112.000000
mean,36.370000,7.60450,69.720000,7.323500,6.079500,6.032500,46845.000000,2.057000,7.745536,114796.428571
std,7.042805,4.25166,15.481277,1.127009,1.731624,1.477025,8858.234394,1.202489,1.226795,28371.311892
min,23.000000,0.00000,31.000000,4.500000,2.000000,2.200000,28000.000000,0.200000,4.300000,50000.000000
25%,31.000000,4.30000,59.750000,6.500000,4.975000,5.000000,39500.000000,1.200000,6.875000,97850.000000
50%,36.000000,7.35000,70.000000,7.300000,6.000000,6.100000,47000.000000,1.950000,7.800000,111450.000000
75%,41.000000,10.22500,82.000000,8.100000,7.325000,6.900000,53625.000000,2.900000,8.500000,131850.000000
max,53.000000,19.40000,98.000000,10.000000,10.000000,10.000000,71500.000000,6.200000,10.000000,196200.000000